export let restricted = [
	// paywall
	'The Wall Street Journal',
	'The New York Times',
	'The Washington Post',
	'Financial Times',
	'CNN',
	'Ground News',
	'Bloomberg',
	'Daily Wire',
	'Le Monde',
	// scrapping issues
	'Reuters',
	'POLITICO',
	'The Hill',
	'Axios',
	'Fortune',
]

export const AgencyLevel = Object.freeze({
	Unknown: 0,
	Other: 1,
	Niche: 2,
	Mainstream: 3,
	Major: 4,
	TopTier: 5,
})

export const defaultAgencyLevel = AgencyLevel.Other

export const agencyLevels = {
	// Level guide: TopTier = wires/majors, Major = national/international, Mainstream = solid mainstream, Niche = niche/local.
	'associated press': AgencyLevel.TopTier,
	'ap news': AgencyLevel.TopTier,
	'reuters': AgencyLevel.TopTier,
	'bloomberg': AgencyLevel.TopTier,
	'financial times': AgencyLevel.TopTier,
	'the wall street journal': AgencyLevel.TopTier,
	'wsj': AgencyLevel.TopTier,

	'the new york times': AgencyLevel.Major,
	'new york times': AgencyLevel.Major,
	'the washington post': AgencyLevel.Major,
	'washington post': AgencyLevel.Major,
	'bbc': AgencyLevel.Major,
	'bbc news': AgencyLevel.Major,
	'the guardian': AgencyLevel.Major,
	'al jazeera': AgencyLevel.Major,
	'npr': AgencyLevel.Major,
	'pbs newshour': AgencyLevel.Major,
	'cnn': AgencyLevel.Major,
	'fox news': AgencyLevel.Major,
	'cnbc': AgencyLevel.Major,
	'politico': AgencyLevel.Major,
	'axios': AgencyLevel.Major,

	'usa today': AgencyLevel.Mainstream,
	'abc news': AgencyLevel.Mainstream,
	'cbs news': AgencyLevel.Mainstream,
	'nbc news': AgencyLevel.Mainstream,
	'time': AgencyLevel.Mainstream,
	'newsweek': AgencyLevel.Mainstream,
	'fortune': AgencyLevel.Mainstream,
	'the hill': AgencyLevel.Mainstream,
	'marketwatch': AgencyLevel.Mainstream,
	'barron\'s': AgencyLevel.Mainstream,
	'propublica': AgencyLevel.Mainstream,
	'los angeles times': AgencyLevel.Mainstream,
	'chicago tribune': AgencyLevel.Mainstream,
	'the boston globe': AgencyLevel.Mainstream,
	'the dallas morning news': AgencyLevel.Mainstream,
	'san francisco chronicle': AgencyLevel.Mainstream,
	'the philadelphia inquirer': AgencyLevel.Mainstream,
	'the atlanta journal-constitution': AgencyLevel.Mainstream,
	'detroit news': AgencyLevel.Mainstream,
	'the miami herald': AgencyLevel.Mainstream,
	'the seattle times': AgencyLevel.Mainstream,
	'kc star': AgencyLevel.Mainstream,
	'kansas city star': AgencyLevel.Mainstream,
	'government technology': AgencyLevel.Mainstream,
	'techcrunch': AgencyLevel.Mainstream,

	'le monde': AgencyLevel.Mainstream,
	'der spiegel': AgencyLevel.Mainstream,
	'france 24': AgencyLevel.Mainstream,
	'euronews': AgencyLevel.Mainstream,
}

export const agencyDomains = {
	'Associated Press': ['apnews.com'],
	'AP News': ['apnews.com'],
	'Reuters': ['reuters.com'],
	'Bloomberg': ['bloomberg.com'],
	'Financial Times': ['ft.com'],
	'The Wall Street Journal': ['wsj.com'],
	'The New York Times': ['nytimes.com'],
	'The Washington Post': ['washingtonpost.com'],
	'BBC': ['bbc.com', 'bbc.co.uk'],
	'The Guardian': ['theguardian.com'],
	'Al Jazeera': ['aljazeera.com'],
	'NPR': ['npr.org'],
	'PBS NewsHour': ['pbs.org', 'pbs.org/newshour'],
	'CNN': ['cnn.com'],
	'Fox News': ['foxnews.com'],
	'CNBC': ['cnbc.com'],
	'Politico': ['politico.com'],
	'Axios': ['axios.com'],
	'USA Today': ['usatoday.com'],
	'ABC News': ['abcnews.go.com'],
	'CBS News': ['cbsnews.com'],
	'NBC News': ['nbcnews.com'],
	'Time': ['time.com'],
	'Newsweek': ['newsweek.com'],
	'Fortune': ['fortune.com'],
	'The Hill': ['thehill.com'],
	'MarketWatch': ['marketwatch.com'],
	"Barron's": ['barrons.com'],
	'ProPublica': ['propublica.org'],
	'Los Angeles Times': ['latimes.com'],
	'Chicago Tribune': ['chicagotribune.com'],
	'The Boston Globe': ['bostonglobe.com'],
	'The Dallas Morning News': ['dallasnews.com'],
	'San Francisco Chronicle': ['sfchronicle.com'],
	'The Philadelphia Inquirer': ['inquirer.com'],
	'The Atlanta Journal-Constitution': ['ajc.com'],
	'Detroit News': ['detroitnews.com'],
	'The Miami Herald': ['miamiherald.com'],
	'The Seattle Times': ['seattletimes.com'],
	'Kansas City Star': ['kansascity.com'],
	'KC Star': ['kansascity.com'],
	'Government Technology': ['govtech.com'],
	'TechCrunch': ['techcrunch.com'],
	'Le Monde': ['lemonde.fr'],
	'Der Spiegel': ['spiegel.de'],
	'France 24': ['france24.com'],
	'Euronews': ['euronews.com'],
}
