import { readEnv } from '../src/env.js'

export let rootFolderId = readEnv('GOOGLE_ROOT_FOLDER_ID', 'GOOGLE_DRIVE_ROOT_FOLDER_ID') || '1nJnHBcY252xqV0JDIidsxxhJkY6-w2WO'
export let mainSpreadsheetId = readEnv('GOOGLE_SHEET_ID_MAIN') || '19Bt7Kov-1lUfc3bOJ-dNkBcTkQPhLMV2W135x0nlctA'
export let autoSpreadsheetId = readEnv('GOOGLE_SHEET_ID_AUTO') || '1aTs8t6wp3Ag7yryH2wci_ETdtNWmDu0ePyf-jLdY9NQ'
export let newsSheet = 'news'
export let aiSheet = 'ai-instructions'
export let promptsSheet = 'prompts'
export let templatePresentationId = readEnv('GOOGLE_TEMPLATE_PRESENTATION_ID', 'GOOGLE_DRIVE_TEMPLATE_ID') || '1Rm5WnQRnEMmw6XDMRIX8l-BZIlt5Sz5CBBtRrzjvpak'
export let templateSlideId = readEnv('GOOGLE_TEMPLATE_SLIDE_ID', 'GOOGLE_DRIVE_TEMPLATE_SLIDE_ID') || 'p'
export let templateTableId = readEnv('GOOGLE_TEMPLATE_TABLE_ID', 'GOOGLE_DRIVE_TEMPLATE_TABLE_ID') || 'g32d1f8c10a8_0_0'
export let presentationName = readEnv('GOOGLE_PRESENTATION_NAME') || 'coffee-maker'
export let autoPresentationName = readEnv('GOOGLE_AUTO_PRESENTATION_NAME') || 'coffee-maker-auto'
export let audioFolderName = 'audio'
export let imageFolderName = 'img'
export let archiveFolderId = '1pNa15MULvOIaGqeQAYfxN9e7FX5cLlgR'
export let autoArchiveFolderId = '17OlCbhRNhkLYSL6aKYMAr_d2oazw_RaX'
